name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  building:
    name: Build and Analyse code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - name: Set up JDK 25
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 #v4.7.0
      with:
        distribution: 'temurin'
        java-version: '25'

    - name: Build and Analyse with Maven
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >
        mvn -B --no-transfer-progress
        clean verify
        org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.organization=mackdk -Dsonar.projectKey=mackdk_obs-maven-plugin
